#!/usr/bin/env php
<?php

declare(strict_types=1);

use Cosmira\Soda\Commands\InitCommand;
use Cosmira\Soda\Commands\ListRulesCommand;
use Cosmira\Soda\Commands\QualityCommand;
use Cosmira\Soda\Application;
use Illuminate\Events\Dispatcher;
use Illuminate\Console\Application as ConsoleApplication;
use Composer\InstalledVersions;
use Cosmira\Soda\Commands\ListMetricsCommand;

$autoloadPaths = [
    __DIR__ . '/vendor/autoload.php',
    __DIR__ . '/../../autoload.php',
];

$autoloadLoaded = false;

foreach ($autoloadPaths as $path) {
    if (file_exists($path)) {
        require $path;
        $autoloadLoaded = true;
        break;
    }
}

if (!$autoloadLoaded) {
    fwrite(STDERR, "Dependencies are missing. Run 'composer install'." . PHP_EOL);
    exit(1);
}

$container = new Application();
$events = new Dispatcher($container);
$version = InstalledVersions::getPrettyVersion('cosmira/soda') ?? '1.0';

$artisan = new ConsoleApplication($container, $events, $version);
$artisan->setName('Soda');
$artisan->setDefaultCommand('quality');
$artisan->setCatchExceptions(true);

// Bind a command
$artisan->resolveCommands([
    InitCommand::class,
    ListRulesCommand::class,
    ListMetricsCommand::class,
    QualityCommand::class,
]);

$status = $artisan->run();

if (! defined('SODA_ENTRY_NO_EXIT')) {
    exit($status);
}

return $status;
