<?php

declare(strict_types=1);

return [
    'max_delegation_depth' => [
        'class'      => 'Cosmira\\Soda\\Rules\\Structure\\MaxDelegationDepth',
        'arguments'  => [3],
        'section'    => 'structural',
        'severity'   => 'error',
        'default'    => 3,
        'label'      => 'Delegation depth:',
        'advice'     => 'Remove transparent forwarding chains; moving each call into another method does not simplify the operation.',
        'comparison' => null,
    ],

    'max_effective_methods_per_class' => [
        'class'      => 'Cosmira\\Soda\\Rules\\Structure\\MaxEffectiveMethodsPerClass',
        'arguments'  => [40],
        'section'    => 'structural',
        'severity'   => 'error',
        'default'    => 40,
        'label'      => 'Methods including traits:',
        'advice'     => 'Keep the complete owning class within its method limit; trait extraction does not reduce this measurement.',
        'comparison' => null,
    ],

    'max_effective_class_length' => [
        'class'      => 'Cosmira\\Soda\\Rules\\Structure\\MaxEffectiveClassLength',
        'arguments'  => [500],
        'section'    => 'structural',
        'severity'   => 'error',
        'default'    => 500,
        'label'      => 'Source lines including traits:',
        'advice'     => 'Count source from all composed traits once; moving source to a trait does not remove its maintenance cost.',
        'comparison' => null,
    ],

    'no_mode_parameters' => [
        'class'      => 'Cosmira\\Soda\\Rules\\Architecture\\NoModeParameters',
        'arguments'  => [],
        'section'    => 'structural',
        'severity'   => 'error',
        'default'    => 0,
        'label'      => 'Mode parameters:',
        'advice'     => 'Expose separate operations instead of selecting distinct operations with an input mode.',
        'comparison' => null,
    ],

    'no_repeated_type_dispatch' => [
        'class'      => 'Cosmira\\Soda\\Rules\\Architecture\\NoRepeatedTypeDispatch',
        'arguments'  => ['minMethods' => 2],
        'section'    => 'structural',
        'severity'   => 'error',
        'default'    => 1,
        'label'      => 'Repeated type dispatch:',
        'advice'     => 'Centralize repeated dispatch of the same type or discriminator family.',
        'comparison' => null,
    ],

    'no_untyped_parameters' => [
        'class'      => 'Cosmira\\Soda\\Rules\\Architecture\\NoUntypedParameters',
        'arguments'  => [],
        'section'    => 'structural',
        'severity'   => 'error',
        'default'    => 0,
        'label'      => 'Untyped parameters:',
        'advice'     => 'Declare accepted parameter types. Use mixed to preserve an untyped inherited contract; do not narrow its accepted inputs.',
        'comparison' => null,
    ],

    'no_unused_private_state' => [
        'class'      => 'Cosmira\\Soda\\Rules\\Usage\\NoUnusedPrivateState',
        'arguments'  => [],
        'section'    => 'structural',
        'severity'   => 'error',
        'default'    => 0,
        'label'      => 'Unread private state:',
        'advice'     => 'Remove private properties and constants that are never read, including composed trait state.',
        'comparison' => null,
    ],

    'no_dependency_cycles' => [
        'class'      => 'Cosmira\\Soda\\Rules\\Architecture\\NoDependencyCycles',
        'arguments'  => [],
        'section'    => 'structural',
        'severity'   => 'error',
        'default'    => 0,
        'label'      => 'Module dependency cycles:',
        'advice'     => 'Remove mutual dependencies between namespace modules; configure namespace prefixes for explicit boundaries.',
        'comparison' => null,
    ],

    'no_empty_local_interfaces' => [
        'class'      => 'Cosmira\\Soda\\Rules\\Architecture\\NoEmptyLocalInterfaces',
        'arguments'  => [],
        'section'    => 'structural',
        'severity'   => 'error',
        'default'    => 0,
        'label'      => 'Empty local interfaces:',
        'advice'     => 'Remove decorative marker interfaces; list required external protocols explicitly.',
        'comparison' => null,
    ],

    'no_redundant_local_interfaces' => [
        'class'      => 'Cosmira\\Soda\\Rules\\Architecture\\NoRedundantLocalInterfaces',
        'arguments'  => [],
        'section'    => 'structural',
        'severity'   => 'error',
        'default'    => 0,
        'label'      => 'Unconsumed local interfaces:',
        'advice'     => 'List externally consumed interfaces in contracts. Remove only unused interfaces; an implements clause alone is not a type consumer for this policy.',
        'comparison' => null,
    ],

    'no_unused_parameters' => [
        'class'      => 'Cosmira\\Soda\\Rules\\Usage\\NoUnusedParameters',
        'arguments'  => [],
        'section'    => 'structural',
        'severity'   => 'error',
        'default'    => 0,
        'label'      => 'Unused parameters:',
        'advice'     => 'Remove unused inputs only when the signature permits it. Known inherited positions and callback slots are preserved; list exact external method contracts.',
        'comparison' => null,
    ],

    'max_method_length' => [
        'class'      => 'Cosmira\\Soda\\Rules\\Structure\\MaxMethodLength',
        'arguments'  => [100],
        'section'    => 'structural',
        'severity'   => 'error',
        'default'    => 100,
        'label'      => 'Method length:',
        'advice'     => 'Name a distinct step with a private method when it clarifies the scenario; keep the operation with its owner.',
        'comparison' => null,
    ],
    'max_class_length' => [
        'class'      => 'Cosmira\\Soda\\Rules\\Structure\\MaxClassLength',
        'arguments'  => [500],
        'section'    => 'structural',
        'severity'   => 'error',
        'default'    => 500,
        'label'      => 'Class length:',
        'advice'     => 'Review the responsibilities together. Keep related behavior local, organize a cohesive concern in a trait, or extract an object with its own state or boundary.',
        'comparison' => null,
    ],
    'max_arguments' => [
        'class'      => 'Cosmira\\Soda\\Rules\\Structure\\MaxArguments',
        'arguments'  => [3],
        'section'    => 'structural',
        'severity'   => 'warning',
        'default'    => 3,
        'label'      => 'Arguments:',
        'advice'     => 'Move behavior to the owner of its data. Use a value object when related arguments share meaning, operations or an invariant; avoid a wrapper solely to reduce this count.',
        'comparison' => null,
    ],
    'max_methods_per_class' => [
        'class'      => 'Cosmira\\Soda\\Rules\\Structure\\MaxMethodsPerClass',
        'arguments'  => [40],
        'section'    => 'structural',
        'severity'   => 'warning',
        'default'    => 40,
        'label'      => 'Methods per class:',
        'advice'     => 'Review the public scenario and unrelated responsibilities. A cohesive concern may stay on the owner as a trait; a new object needs a distinct purpose.',
        'comparison' => null,
    ],
    'max_file_loc' => [
        'class'      => 'Cosmira\\Soda\\Rules\\Structure\\MaxFileLoc',
        'arguments'  => [700],
        'section'    => 'structural',
        'severity'   => 'warning',
        'default'    => 700,
        'label'      => 'File LOC:',
        'advice'     => 'Split the file by responsibility; keep one primary type or cohesive concern per file.',
        'comparison' => null,
    ],
    'max_line_length' => [
        'class'      => 'Cosmira\\Soda\\Rules\\Structure\\MaxLineLength',
        'arguments'  => [100],
        'section'    => 'structural',
        'severity'   => 'warning',
        'default'    => 100,
        'label'      => 'Line length:',
        'advice'     => 'Name the intermediate value or wrap the expression so each line communicates one idea.',
        'comparison' => null,
    ],
    'max_properties_per_class' => [
        'class'      => 'Cosmira\\Soda\\Rules\\Structure\\MaxPropertiesPerClass',
        'arguments'  => [5],
        'section'    => 'structural',
        'severity'   => 'warning',
        'default'    => 5,
        'label'      => 'Properties per class:',
        'advice'     => 'Keep state with its behavior. Group values when they share meaning or invariants; a property count alone does not justify another object.',
        'comparison' => null,
    ],
    'max_public_methods' => [
        'class'      => 'Cosmira\\Soda\\Rules\\Structure\\MaxPublicMethods',
        'arguments'  => [20],
        'section'    => 'structural',
        'severity'   => 'warning',
        'default'    => 20,
        'label'      => 'Public methods:',
        'advice'     => 'Review which operations callers need. Supporting behavior can remain private on its owner; preserve useful fluent operations and framework contracts.',
        'comparison' => null,
    ],
    'max_dependencies' => [
        'class'      => 'Cosmira\\Soda\\Rules\\Structure\\MaxDependencies',
        'arguments'  => [8],
        'section'    => 'structural',
        'severity'   => 'warning',
        'default'    => 8,
        'label'      => 'Dependencies:',
        'advice'     => 'Review which dependencies belong to the same operation. Extract only an independently useful responsibility; another forwarding service does not remove coupling.',
        'comparison' => null,
    ],
    'max_todo_fixme_comments' => [
        'class'      => 'Cosmira\\Soda\\Rules\\Structure\\NoTodoFixmeComments',
        'arguments'  => [],
        'section'    => 'structural',
        'severity'   => 'warning',
        'default'    => 0,
        'label'      => 'TODO/FIXME comments:',
        'advice'     => 'Resolve the debt now or track it externally with context; do not leave an anonymous promise in the code.',
        'comparison' => null,
    ],
    'max_commented_out_code_lines' => [
        'class'      => 'Cosmira\\Soda\\Rules\\Structure\\NoCommentedOutCode',
        'arguments'  => [],
        'section'    => 'structural',
        'severity'   => 'warning',
        'default'    => 0,
        'label'      => 'Commented-out code lines:',
        'advice'     => 'Delete dead code and trust version control; preserve an explanation only when it documents why.',
        'comparison' => null,
    ],
    'max_empty_catch_blocks' => [
        'class'      => 'Cosmira\\Soda\\Rules\\Structure\\NoEmptyCatchBlocks',
        'arguments'  => [],
        'section'    => 'structural',
        'severity'   => 'warning',
        'default'    => 0,
        'label'      => 'Empty catch blocks:',
        'advice'     => 'Handle the failure, translate it to a domain outcome, or document explicitly why ignoring it is safe.',
        'comparison' => null,
    ],
    'max_ask_then_tell_patterns' => [
        'class'      => 'Cosmira\\Soda\\Rules\\Structure\\NoAskThenTellPatterns',
        'arguments'  => [],
        'section'    => 'structural',
        'severity'   => 'warning',
        'default'    => 0,
        'label'      => 'Ask-then-tell patterns:',
        'advice'     => 'Tell the object what outcome you want instead of querying its state and deciding for it.',
        'comparison' => null,
    ],
    'no_trivial_delegating_classes' => [
        'class'      => 'Cosmira\\Soda\\Rules\\Structure\\NoTrivialDelegatingClasses',
        'arguments'  => [],
        'section'    => 'structural',
        'severity'   => 'warning',
        'default'    => 0,
        'label'      => 'Trivial delegating classes:',
        'advice'     => 'Call the collaborator directly when the wrapper adds no concept. Keep genuine adapters and boundaries; adding an interface alone does not simplify the call path.',
        'comparison' => null,
    ],
    'methods_follow_call_order' => [
        'class'      => 'Cosmira\\Soda\\Rules\\Structure\\MethodsFollowCallOrder',
        'arguments'  => [],
        'section'    => 'structural',
        'severity'   => 'warning',
        'default'    => 0,
        'label'      => 'Methods out of call order:',
        'advice'     => 'Place the called helper directly below its caller so the class reads from high-level intent to detail.',
        'comparison' => null,
    ],
    'only_list_arrays' => [
        'class'      => 'Cosmira\\Soda\\Rules\\Usage\\OnlyListArraysAllowed',
        'arguments'  => [],
        'section'    => 'structural',
        'severity'   => 'warning',
        'default'    => 0,
        'label'      => 'Nested array chains (list-only / strict opt-in):',
        'advice'     => 'This checks array-access syntax. Use a value object for repeated domain interpretation or invariants; transport payloads and one-off arrays do not automatically need wrappers.',
        'comparison' => null,
    ],
    'no_numeric_array_index' => [
        'class'      => 'Cosmira\\Soda\\Rules\\Usage\\NoNumericArrayIndex',
        'arguments'  => [],
        'section'    => 'structural',
        'severity'   => 'warning',
        'default'    => 0,
        'label'      => 'Numeric array index:',
        'advice'     => 'Use a named field or value object so readers do not need to remember what this position means.',
        'comparison' => null,
    ],
    'unused_methods' => [
        'class'      => 'Cosmira\\Soda\\Rules\\Usage\\NoUnusedMethods',
        'arguments'  => [],
        'section'    => 'structural',
        'severity'   => 'warning',
        'default'    => 0,
        'label'      => 'Unused methods:',
        'advice'     => 'Delete the method; if it is an intended extension point, express that contract explicitly.',
        'comparison' => null,
    ],
    'useless_variable' => [
        'class'      => 'Cosmira\\Soda\\Rules\\Usage\\UselessVariableRule',
        'arguments'  => [],
        'section'    => 'structural',
        'severity'   => 'warning',
        'default'    => 0,
        'label'      => 'Useless variable:',
        'advice'     => 'Inline the value when the name adds nothing, or use the variable where its name clarifies intent.',
        'comparison' => null,
    ],
    'no_assignment_in_condition' => [
        'class'      => 'Cosmira\\Soda\\Rules\\Complexity\\NoAssignmentInCondition',
        'arguments'  => [],
        'section'    => 'structural',
        'severity'   => 'warning',
        'default'    => 0,
        'label'      => 'Assignments inside conditions:',
        'advice'     => 'Assign first, then make the condition a pure question with no hidden state change.',
        'comparison' => null,
    ],
    'no_else_branches' => [
        'class'      => 'Cosmira\\Soda\\Rules\\Complexity\\NoElseBranches',
        'arguments'  => [],
        'section'    => 'structural',
        'severity'   => 'warning',
        'default'    => 0,
        'label'      => 'Else/elseif branches:',
        'advice'     => 'Use guard clauses and early exits so the remaining happy path stays flat and explicit.',
        'comparison' => null,
    ],
    'no_complex_control_conditions' => [
        'class'      => 'Cosmira\\Soda\\Rules\\Complexity\\NoComplexControlConditions',
        'arguments'  => [],
        'section'    => 'structural',
        'severity'   => 'warning',
        'default'    => 0,
        'label'      => 'Complex control conditions:',
        'advice'     => 'Keep simple predicates, comparisons and homogeneous boolean chains inline. Name mixed decisions or prepare nested computations locally.',
        'comparison' => null,
    ],
    'no_service_locator_calls' => [
        'class'      => 'Cosmira\\Soda\\Rules\\Architecture\\NoServiceLocatorCalls',
        'arguments'  => [],
        'section'    => 'structural',
        'severity'   => 'warning',
        'default'    => 0,
        'label'      => 'Service locator calls:',
        'advice'     => 'Declare dependencies in the constructor instead of pulling them from a global container.',
        'comparison' => null,
    ],
    'no_singleton_access' => [
        'class'      => 'Cosmira\\Soda\\Rules\\Architecture\\NoSingletonAccess',
        'arguments'  => [],
        'section'    => 'structural',
        'severity'   => 'warning',
        'default'    => 0,
        'label'      => 'Singleton access:',
        'advice'     => 'Construct collaborators at the composition root and inject their explicit lifetime.',
        'comparison' => null,
    ],
    'no_reflection' => [
        'class'      => 'Cosmira\\Soda\\Rules\\Architecture\\NoReflection',
        'arguments'  => [],
        'section'    => 'structural',
        'severity'   => 'warning',
        'default'    => 0,
        'label'      => 'Reflection usage:',
        'advice'     => 'Replace reflective construction with explicit factories, mapping, or framework conventions.',
        'comparison' => null,
    ],
    'no_runtime_hooks' => [
        'class'      => 'Cosmira\\Soda\\Rules\\Architecture\\NoRuntimeHooks',
        'arguments'  => [],
        'section'    => 'structural',
        'severity'   => 'warning',
        'default'    => 0,
        'label'      => 'Runtime hooks:',
        'advice'     => 'Register lifecycle and error handling once at an explicit application boundary.',
        'comparison' => null,
    ],
    'no_runtime_code_evaluation' => [
        'class'      => 'Cosmira\\Soda\\Rules\\Architecture\\NoRuntimeCodeEvaluation',
        'arguments'  => [],
        'section'    => 'structural',
        'severity'   => 'warning',
        'default'    => 0,
        'label'      => 'Runtime code evaluation:',
        'advice'     => 'Represent policy as typed code or validated data instead of evaluating generated source.',
        'comparison' => null,
    ],
    'no_process_configuration_mutation' => [
        'class'      => 'Cosmira\\Soda\\Rules\\Architecture\\NoProcessConfigurationMutation',
        'arguments'  => [],
        'section'    => 'structural',
        'severity'   => 'warning',
        'default'    => 0,
        'label'      => 'Process configuration mutation:',
        'advice'     => 'Configure ini, cwd, locale, and timezone once at the composition boundary.',
        'comparison' => null,
    ],
    'no_direct_response_globals' => [
        'class'      => 'Cosmira\\Soda\\Rules\\Architecture\\NoDirectResponseGlobals',
        'arguments'  => [],
        'section'    => 'structural',
        'severity'   => 'warning',
        'default'    => 0,
        'label'      => 'Direct response globals:',
        'advice'     => 'Return an explicit response and isolate headers, cookies, and sessions in adapters.',
        'comparison' => null,
    ],
    'no_symbol_table_mutation' => [
        'class'      => 'Cosmira\\Soda\\Rules\\Architecture\\NoSymbolTableMutation',
        'arguments'  => [],
        'section'    => 'structural',
        'severity'   => 'warning',
        'default'    => 0,
        'label'      => 'Symbol-table mutation:',
        'advice'     => 'Map named input fields explicitly instead of manufacturing local variables.',
        'comparison' => null,
    ],
    'no_implicit_arguments' => [
        'class'      => 'Cosmira\\Soda\\Rules\\Architecture\\NoImplicitArguments',
        'arguments'  => [],
        'section'    => 'structural',
        'severity'   => 'warning',
        'default'    => 0,
        'label'      => 'Implicit arguments:',
        'advice'     => 'Declare the callable contract with named parameters or a typed command object.',
        'comparison' => null,
    ],
    'no_direct_filesystem_mutation' => [
        'class'      => 'Cosmira\\Soda\\Rules\\Architecture\\NoDirectFilesystemMutation',
        'arguments'  => [],
        'section'    => 'structural',
        'severity'   => 'warning',
        'default'    => 0,
        'label'      => 'Direct filesystem mutation:',
        'advice'     => 'Move writes, deletes, moves, and provisioning behind an injected storage port.',
        'comparison' => null,
    ],
    'no_subprocess_execution' => [
        'class'      => 'Cosmira\\Soda\\Rules\\Architecture\\NoSubprocessExecution',
        'arguments'  => [],
        'section'    => 'structural',
        'severity'   => 'warning',
        'default'    => 0,
        'label'      => 'Subprocess execution:',
        'advice'     => 'Wrap the external capability in a typed gateway with explicit failures.',
        'comparison' => null,
    ],
    'no_native_deserialization' => [
        'class'      => 'Cosmira\\Soda\\Rules\\Architecture\\NoNativeDeserialization',
        'arguments'  => [],
        'section'    => 'structural',
        'severity'   => 'warning',
        'default'    => 0,
        'label'      => 'Native deserialization:',
        'advice'     => 'Decode validated scalar data and construct allowed types explicitly.',
        'comparison' => null,
    ],
    'no_runtime_includes' => [
        'class'      => 'Cosmira\\Soda\\Rules\\Architecture\\NoRuntimeIncludes',
        'arguments'  => [],
        'section'    => 'structural',
        'severity'   => 'warning',
        'default'    => 0,
        'label'      => 'Runtime includes:',
        'advice'     => 'Use autoloaded collaborators or validated data configuration instead of runtime includes.',
        'comparison' => null,
    ],
    'no_runtime_type_aliases' => [
        'class'      => 'Cosmira\\Soda\\Rules\\Architecture\\NoRuntimeTypeAliases',
        'arguments'  => [],
        'section'    => 'structural',
        'severity'   => 'warning',
        'default'    => 0,
        'label'      => 'Runtime type aliases:',
        'advice'     => 'Migrate callers explicitly or introduce a visible adapter type.',
        'comparison' => null,
    ],
    'no_dynamic_properties' => [
        'class'      => 'Cosmira\\Soda\\Rules\\Architecture\\NoDynamicProperties',
        'arguments'  => [],
        'section'    => 'structural',
        'severity'   => 'warning',
        'default'    => 0,
        'label'      => 'Dynamic properties:',
        'advice'     => 'Declare typed state or hydrate a named value object with a stable shape.',
        'comparison' => null,
    ],
    'no_anonymous_classes' => [
        'class'      => 'Cosmira\\Soda\\Rules\\Architecture\\NoAnonymousClasses',
        'arguments'  => [],
        'section'    => 'structural',
        'severity'   => 'warning',
        'default'    => 0,
        'label'      => 'Anonymous classes:',
        'advice'     => 'Promote the hidden responsibility to a named, independently testable type.',
        'comparison' => null,
    ],
    'no_object_cloning' => [
        'class'      => 'Cosmira\\Soda\\Rules\\Architecture\\NoObjectCloning',
        'arguments'  => [],
        'section'    => 'structural',
        'severity'   => 'warning',
        'default'    => 0,
        'label'      => 'Object cloning:',
        'advice'     => 'This policy forbids every clone, including explicit copying APIs. Fresh construction satisfies it; clone-based value APIs require choosing a different rule selection.',
        'comparison' => null,
    ],
    'no_closure_rebinding' => [
        'class'      => 'Cosmira\\Soda\\Rules\\Architecture\\NoClosureRebinding',
        'arguments'  => [],
        'section'    => 'structural',
        'severity'   => 'warning',
        'default'    => 0,
        'label'      => 'Closure rebinding:',
        'advice'     => 'Pass an explicit collaborator instead of changing a closure scope at runtime.',
        'comparison' => null,
    ],
    'no_runtime_contract_probes' => [
        'class'      => 'Cosmira\\Soda\\Rules\\Architecture\\NoRuntimeContractProbes',
        'arguments'  => [],
        'section'    => 'structural',
        'severity'   => 'warning',
        'default'    => 0,
        'label'      => 'Runtime contract probes:',
        'advice'     => 'Require an interface or typed value instead of discovering capabilities at runtime.',
        'comparison' => null,
    ],
    'no_global_state' => [
        'class'      => 'Cosmira\\Soda\\Rules\\Architecture\\NoGlobalState',
        'arguments'  => [],
        'section'    => 'structural',
        'severity'   => 'warning',
        'default'    => 0,
        'label'      => 'Global state access:',
        'advice'     => 'Pass state explicitly through arguments or an injected state owner.',
        'comparison' => null,
    ],
    'no_environment_reads' => [
        'class'      => 'Cosmira\\Soda\\Rules\\Architecture\\NoEnvironmentReads',
        'arguments'  => [],
        'section'    => 'structural',
        'severity'   => 'warning',
        'default'    => 0,
        'label'      => 'Environment reads:',
        'advice'     => 'Read environment variables once at the application boundary and inject typed configuration.',
        'comparison' => null,
    ],
    'no_error_suppression' => [
        'class'      => 'Cosmira\\Soda\\Rules\\Architecture\\NoErrorSuppression',
        'arguments'  => [],
        'section'    => 'structural',
        'severity'   => 'warning',
        'default'    => 0,
        'label'      => 'Suppressed errors:',
        'advice'     => 'Handle, translate, or deliberately propagate the failure instead of hiding it.',
        'comparison' => null,
    ],
    'no_dynamic_invocation' => [
        'class'      => 'Cosmira\\Soda\\Rules\\Architecture\\NoDynamicInvocation',
        'arguments'  => [],
        'section'    => 'structural',
        'severity'   => 'warning',
        'default'    => 0,
        'label'      => 'Dynamic invocations:',
        'advice'     => 'Replace runtime-selected callables with an explicit interface or named dispatch map.',
        'comparison' => null,
    ],
    'no_catch_all_exceptions' => [
        'class'      => 'Cosmira\\Soda\\Rules\\Architecture\\NoCatchAllExceptions',
        'arguments'  => [],
        'section'    => 'structural',
        'severity'   => 'warning',
        'default'    => 0,
        'label'      => 'Catch-all exceptions:',
        'advice'     => 'Catch only failures the current boundary can recover from meaningfully.',
        'comparison' => null,
    ],
    'no_boolean_parameters' => [
        'class'      => 'Cosmira\\Soda\\Rules\\Architecture\\NoBooleanParameters',
        'arguments'  => [],
        'section'    => 'structural',
        'severity'   => 'warning',
        'default'    => 0,
        'label'      => 'Boolean parameters:',
        'advice'     => 'Separate behavior selected by a mode flag with named methods when useful. Boolean state is data; the rule recognizes direct readonly initialization, not every valid data flow.',
        'comparison' => null,
    ],
    'no_behavior_magic_methods' => [
        'class'      => 'Cosmira\\Soda\\Rules\\Architecture\\NoBehaviorMagicMethods',
        'arguments'  => [],
        'section'    => 'structural',
        'severity'   => 'warning',
        'default'    => 0,
        'label'      => 'Behavior magic methods:',
        'advice'     => 'Expose explicit methods so callers and tools can see the supported contract.',
        'comparison' => null,
    ],
    'no_static_mutable_properties' => [
        'class'      => 'Cosmira\\Soda\\Rules\\Architecture\\NoStaticMutableProperties',
        'arguments'  => [],
        'section'    => 'structural',
        'severity'   => 'warning',
        'default'    => 0,
        'label'      => 'Static mutable state:',
        'advice'     => 'Put shared mutable state in an injected object with explicit lifetime and ownership.',
        'comparison' => null,
    ],
    'no_blocking_sleep' => [
        'class'      => 'Cosmira\\Soda\\Rules\\Architecture\\NoBlockingSleep',
        'arguments'  => [],
        'section'    => 'structural',
        'severity'   => 'warning',
        'default'    => 0,
        'label'      => 'Blocking sleeps:',
        'advice'     => 'Inject time and retry coordination rather than blocking inside application behavior.',
        'comparison' => null,
    ],
    'max_efferent_coupling' => [
        'class'      => 'Cosmira\\Soda\\Rules\\Structure\\MaxEfferentCoupling',
        'arguments'  => [10],
        'section'    => 'structural',
        'severity'   => 'warning',
        'default'    => 10,
        'label'      => 'Efferent coupling (Ce):',
        'advice'     => 'Review which dependencies belong to this operation. Remove unnecessary indirection; introduce a boundary only when it represents a meaningful collaboration, not merely to lower the count.',
        'comparison' => null,
    ],
    'max_classes_per_file' => [
        'class'      => 'Cosmira\\Soda\\Rules\\Structure\\MaxClassesPerFile',
        'arguments'  => [1],
        'section'    => 'structural',
        'severity'   => 'warning',
        'default'    => 1,
        'label'      => 'Classes per file:',
        'advice'     => 'Move each class to its own file unless the smaller types are inseparable implementation details.',
        'comparison' => null,
    ],
    'max_namespace_depth' => [
        'class'      => 'Cosmira\\Soda\\Rules\\Structure\\MaxNamespaceDepth',
        'arguments'  => [4],
        'section'    => 'structural',
        'severity'   => 'warning',
        'default'    => 4,
        'label'      => 'Namespace depth:',
        'advice'     => 'Flatten the namespace around a clear domain capability; avoid encoding the entire directory tree.',
        'comparison' => null,
    ],
    'max_classes_per_namespace' => [
        'class'      => 'Cosmira\\Soda\\Rules\\Structure\\MaxClassesPerNamespace',
        'arguments'  => [15],
        'section'    => 'structural',
        'severity'   => 'warning',
        'default'    => 15,
        'label'      => 'Classes per namespace:',
        'advice'     => 'Split the namespace into cohesive domain capabilities with names that explain their responsibility.',
        'comparison' => null,
    ],
    'max_layer_dominance_percentage' => [
        'class'      => 'Cosmira\\Soda\\Rules\\Structure\\MaxLayerDominancePercentage',
        'arguments'  => [50, 4],
        'section'    => 'structural',
        'severity'   => 'error',
        'default'    => 50,
        'label'      => 'Layer mixing:',
        'advice'     => 'This is a naming and directory convention, not a dependency analysis. Inspect actual responsibilities and call paths; renaming a folder alone does not improve architecture.',
        'comparison' => null,
    ],
    'max_traits_per_class' => [
        'class'      => 'Cosmira\\Soda\\Rules\\Structure\\MaxTraitsPerClass',
        'arguments'  => [10],
        'section'    => 'structural',
        'severity'   => 'warning',
        'default'    => 10,
        'label'      => 'Traits per class:',
        'advice'     => 'Review the state and methods each trait expects. Keep cohesive concerns on their owner, even with one consumer; avoid extraction solely to reduce this count.',
        'comparison' => null,
    ],
    'max_interfaces_per_class' => [
        'class'      => 'Cosmira\\Soda\\Rules\\Structure\\MaxInterfacesPerClass',
        'arguments'  => [5],
        'section'    => 'structural',
        'severity'   => 'warning',
        'default'    => 5,
        'label'      => 'Interfaces per class:',
        'advice'     => 'Split unrelated roles into focused objects rather than making one class satisfy every contract.',
        'comparison' => null,
    ],
    'max_classes_per_project' => [
        'class'      => 'Cosmira\\Soda\\Rules\\Structure\\MaxClassesPerProject',
        'arguments'  => [300],
        'section'    => 'structural',
        'severity'   => 'error',
        'default'    => 300,
        'label'      => 'Classes per project:',
        'advice'     => 'Look for fragmented abstractions and merge types that do not own distinct behavior or policy.',
        'comparison' => null,
    ],
    'max_cyclomatic_complexity' => [
        'class'      => 'Cosmira\\Soda\\Rules\\Complexity\\MaxCyclomaticComplexity',
        'arguments'  => [8],
        'section'    => 'complexity',
        'severity'   => 'error',
        'default'    => 8,
        'label'      => 'Cyclomatic complexity:',
        'advice'     => 'Review branches and duplicate decisions. Guards can reduce nesting but do not reduce this score; use a private method for a named step or an object for an independent responsibility.',
        'comparison' => null,
    ],
    'max_control_nesting' => [
        'class'      => 'Cosmira\\Soda\\Rules\\Complexity\\MaxControlNesting',
        'arguments'  => [3],
        'section'    => 'complexity',
        'severity'   => 'error',
        'default'    => 3,
        'label'      => 'Control structure nesting:',
        'advice'     => 'Return early for exceptional paths and extract the nested happy-path behavior into a named method.',
        'comparison' => null,
    ],
    'max_return_statements' => [
        'class'      => 'Cosmira\\Soda\\Rules\\Complexity\\MaxReturnStatements',
        'arguments'  => [4],
        'section'    => 'complexity',
        'severity'   => 'warning',
        'default'    => 4,
        'label'      => 'Return statements:',
        'advice'     => 'This counts all returns, including guards. Review the whole scenario alongside nesting; do not add intermediary classes solely to move exits elsewhere.',
        'comparison' => null,
    ],
    'max_boolean_conditions' => [
        'class'      => 'Cosmira\\Soda\\Rules\\Complexity\\MaxBooleanConditions',
        'arguments'  => [4],
        'section'    => 'complexity',
        'severity'   => 'warning',
        'default'    => 4,
        'label'      => 'Boolean conditions:',
        'advice'     => 'Give a repeated or complex decision a useful name, usually with a local value or private predicate. A policy object needs an independent responsibility.',
        'comparison' => null,
    ],
    'max_try_catch_blocks' => [
        'class'      => 'Cosmira\\Soda\\Rules\\Complexity\\MaxTryCatchBlocks',
        'arguments'  => [2],
        'section'    => 'complexity',
        'severity'   => 'warning',
        'default'    => 2,
        'label'      => 'Try/catch blocks:',
        'advice'     => 'Catch failures at one boundary and translate them once instead of mixing recovery with core behavior.',
        'comparison' => null,
    ],
    'avoid_redundant_naming' => [
        'class'      => 'Cosmira\\Soda\\Rules\\Naming\\AvoidRedundantNaming',
        'arguments'  => [80],
        'section'    => 'naming',
        'severity'   => 'warning',
        'default'    => 80,
        'label'      => 'Redundant naming:',
        'advice'     => 'Remove words already supplied by the class or namespace; let the local context carry that meaning.',
        'comparison' => null,
    ],
    'boolean_methods_without_prefix' => [
        'class'      => 'Cosmira\\Soda\\Rules\\Naming\\BooleanMethodPrefix',
        'arguments'  => [],
        'section'    => 'naming',
        'severity'   => 'warning',
        'default'    => 0,
        'label'      => 'Boolean method prefixes:',
        'advice'     => 'Name the method as a question with is, has, can, should, or another explicit predicate prefix.',
        'comparison' => null,
    ],
    'variable_name_length' => [
        'class'     => 'Cosmira\\Soda\\Rules\\Naming\\VariableNameLength',
        'arguments' => [
            'min' => 3,
            'max' => 16,
        ],
        'section'    => 'naming',
        'severity'   => 'warning',
        'default'    => 16,
        'label'      => 'Variable name length:',
        'advice'     => 'Choose a concise domain name: avoid both cryptic abbreviations and sentence-like identifiers.',
        'comparison' => null,
    ],
    'method_name_length' => [
        'class'     => 'Cosmira\\Soda\\Rules\\Naming\\MethodNameLength',
        'arguments' => [
            'min' => 3,
            'max' => 32,
        ],
        'section'    => 'naming',
        'severity'   => 'warning',
        'default'    => 32,
        'label'      => 'Method name length:',
        'advice'     => 'Name one clear action; if the name needs several clauses, split the method’s responsibilities.',
        'comparison' => null,
    ],
    'class_name_length' => [
        'class'     => 'Cosmira\\Soda\\Rules\\Naming\\ClassNameLength',
        'arguments' => [
            'min' => 3,
            'max' => 32,
        ],
        'section'    => 'naming',
        'severity'   => 'warning',
        'default'    => 32,
        'label'      => 'Class name length:',
        'advice'     => 'Name one domain role; a compound sentence usually signals that the class owns multiple responsibilities.',
        'comparison' => null,
    ],
    'namespace_name_length' => [
        'class'     => 'Cosmira\\Soda\\Rules\\Naming\\NamespaceNameLength',
        'arguments' => [
            'min' => 3,
            'max' => 32,
        ],
        'section'    => 'naming',
        'severity'   => 'warning',
        'default'    => 32,
        'label'      => 'Namespace name length:',
        'advice'     => 'Use a short domain term for the capability and remove organizational words that add no distinction.',
        'comparison' => null,
    ],
    'no_redundant_rethrow' => [
        'class'      => 'Cosmira\\Soda\\Rules\\Complexity\\NoRedundantRethrow',
        'arguments'  => [],
        'section'    => 'complexity',
        'severity'   => 'warning',
        'default'    => 0,
        'label'      => 'Redundant rethrow:',
        'advice'     => 'Review a catch that only rethrows. Keep logging, translation, variable bindings and shielding of later handlers intact.',
        'comparison' => null,
        'standard'   => false,
    ],
    'no_empty_finally_blocks' => [
        'class'      => 'Cosmira\\Soda\\Rules\\Complexity\\NoEmptyFinallyBlocks',
        'arguments'  => [],
        'section'    => 'complexity',
        'severity'   => 'warning',
        'default'    => 0,
        'label'      => 'Empty finally blocks:',
        'advice'     => 'Remove empty cleanup syntax carefully; a try without catch cannot remain alone. Preserve meaningful explanations.',
        'comparison' => null,
        'standard'   => false,
    ],
    'max_cognitive_complexity' => [
        'class'      => 'Cosmira\\Soda\\Rules\\Complexity\\MaxCognitiveComplexity',
        'arguments'  => [15],
        'section'    => 'complexity',
        'severity'   => 'warning',
        'default'    => 15,
        'label'      => 'Cognitive complexity (research):',
        'advice'     => 'Inspect the reported evidence in the calling scenario. This experimental measurement does not mandate more classes, traits or value objects.',
        'comparison' => null,
        'standard'   => false,
    ],
    'no_trivial_factories' => [
        'class'      => 'Cosmira\\Soda\\Rules\\Structure\\NoTrivialFactories',
        'arguments'  => [],
        'section'    => 'structural',
        'severity'   => 'warning',
        'default'    => 0,
        'label'      => 'Trivial factories:',
        'advice'     => 'Consider direct construction. Preserve parameter and return type contracts, named arguments and useful creation boundaries.',
        'comparison' => null,
    ],
    'no_repeated_compound_conditions' => [
        'class'      => 'Cosmira\\Soda\\Rules\\Complexity\\NoRepeatedCompoundConditions',
        'arguments'  => ['minMethods' => 3],
        'section'    => 'complexity',
        'severity'   => 'warning',
        'default'    => 2,
        'label'      => 'Methods repeating a compound condition:',
        'advice'     => 'Extract a named predicate when the repeated conditions express the same decision. Reevaluate it at each use; do not cache mutable state.',
        'comparison' => 'max',
    ],
];
