<?php

declare(strict_types=1);

return [
    'file' => [
        'loc' => [
            'type'        => 'number',
            'unit'        => 'logical lines',
            'description' => 'Logical PHP lines excluding blank/comment-only lines. Physical locations remain one-based source lines.',
            'source'      => 'Cosmira\\Soda\\Analysis\\LogicalLineMap::count',
            'analysis'    => null,
        ],
        'classes' => [
            'type'        => 'number',
            'unit'        => 'declarations',
            'description' => 'Named classes and traits. Interfaces, enums and anonymous classes do not contribute to this legacy count.',
            'source'      => 'Cosmira\\Soda\\Analysis\\StructureVisitor::metrics',
            'analysis'    => null,
        ],
        'path' => [
            'type'        => 'string',
            'unit'        => 'text',
            'description' => 'File path with forward slashes.',
            'source'      => 'Cosmira\\Soda\\Analysis\\FileFacts::rows',
            'analysis'    => null,
        ],
    ],
    'class' => [
        'loc' => [
            'type'        => 'number',
            'unit'        => 'logical lines',
            'description' => 'Logical lines in the type declaration, excluding blank/comment-only lines.',
            'source'      => 'Cosmira\\Soda\\Analysis\\StructureVisitor::metrics',
            'analysis'    => null,
        ],
        'methods' => [
            'type'        => 'number',
            'unit'        => 'methods',
            'description' => 'Methods declared directly in this type.',
            'source'      => 'Cosmira\\Soda\\Analysis\\StructureVisitor::metrics',
            'analysis'    => null,
        ],
        'properties' => [
            'type'        => 'number',
            'unit'        => 'properties',
            'description' => 'Effective property identities including known parents and traits in project checks.',
            'source'      => 'Cosmira\\Soda\\Analysis\\ProjectFacts::resolveClasses',
            'analysis'    => null,
        ],
        'public_methods' => [
            'type'        => 'number',
            'unit'        => 'methods',
            'description' => 'Effective public method names including known parents, trait aliases and visibility adaptations.',
            'source'      => 'Cosmira\\Soda\\Analysis\\ProjectFacts::resolveClasses',
            'analysis'    => null,
        ],
        'dependencies' => [
            'type'        => 'number',
            'unit'        => 'dependencies',
            'description' => 'Number of directly declared constructor parameters, including untyped, scalar and promoted parameters.',
            'source'      => 'Cosmira\\Soda\\Analysis\\StructureVisitor::metrics',
            'analysis'    => null,
        ],
        'efferent_coupling' => [
            'type'        => 'number',
            'unit'        => 'types',
            'description' => 'Distinct referenced external types found in static PHP syntax; dynamic names cannot be resolved.',
            'source'      => 'Cosmira\\Soda\\Analysis\\EfferentCouplingVisitor::couplingCountsByClass',
            'analysis'    => 'coupling',
        ],
        'traits' => [
            'type'        => 'number',
            'unit'        => 'traits',
            'description' => 'Direct trait uses counted for this type.',
            'source'      => 'Cosmira\\Soda\\Analysis\\StructureVisitor::metrics',
            'analysis'    => null,
        ],
        'interfaces' => [
            'type'        => 'number',
            'unit'        => 'interfaces',
            'description' => 'Effective implemented interfaces including known parent interfaces and classes.',
            'source'      => 'Cosmira\\Soda\\Analysis\\ProjectFacts::resolveClasses',
            'analysis'    => null,
        ],
        'namespace_depth' => [
            'type'        => 'number',
            'unit'        => 'segments',
            'description' => 'Number of namespace segments; the global namespace has depth zero.',
            'source'      => 'Cosmira\\Soda\\Analysis\\StructureVisitor::metrics',
            'analysis'    => null,
        ],
        'path' => [
            'type'        => 'string',
            'unit'        => 'text',
            'description' => 'File path with forward slashes.',
            'source'      => 'Cosmira\\Soda\\Analysis\\FileFacts::rows',
            'analysis'    => null,
        ],
        'name' => [
            'type'        => 'string',
            'unit'        => 'text',
            'description' => 'Qualified type or callable name.',
            'source'      => 'Cosmira\\Soda\\Analysis\\FileFacts::rows',
            'analysis'    => null,
        ],
        'namespace' => [
            'type'        => 'string',
            'unit'        => 'text',
            'description' => 'Declared namespace; empty for the global namespace.',
            'source'      => 'Cosmira\\Soda\\Analysis\\FileFacts::rows',
            'analysis'    => null,
        ],
        'depends_on' => [
            'type'        => 'dependencies',
            'unit'        => 'type names',
            'description' => 'Referenced static types, resolved using imports; includes attributes. Supports glob matching.',
            'source'      => 'Cosmira\\Soda\\Analysis\\EfferentCouplingVisitor::dependenciesByClass',
            'analysis'    => 'coupling',
        ],
    ],
    'method' => [
        'loc' => [
            'type'        => 'number',
            'unit'        => 'logical lines',
            'description' => 'Logical lines in the callable declaration, excluding blank/comment-only lines.',
            'source'      => 'Cosmira\\Soda\\Analysis\\StructureVisitor::metrics',
            'analysis'    => null,
        ],
        'args' => [
            'type'        => 'number',
            'unit'        => 'parameters',
            'description' => 'Declared parameters, including promoted parameters; variadic parameters count as one.',
            'source'      => 'Cosmira\\Soda\\Analysis\\StructureVisitor::metrics',
            'analysis'    => null,
        ],
        'complexity' => [
            'type'        => 'number',
            'unit'        => 'paths',
            'description' => 'Cyclomatic complexity starts at 1. Nested callable/class bodies are excluded from the owner.',
            'source'      => 'Cosmira\\Soda\\Analysis\\ComplexityVisitor::complexity',
            'analysis'    => 'complexity',
        ],
        'nesting' => [
            'type'        => 'number',
            'unit'        => 'levels',
            'description' => 'Maximum control nesting attributed to this callable; nested callable scopes are separate.',
            'source'      => 'Cosmira\\Soda\\Analysis\\CallableMetricsVisitor::nestingByMethod',
            'analysis'    => 'nesting',
        ],
        'returns' => [
            'type'        => 'number',
            'unit'        => 'statements',
            'description' => 'Return statements belonging to this callable, excluding nested functions and closures.',
            'source'      => 'Cosmira\\Soda\\Analysis\\CallableMetricsVisitor::returnsByMethod',
            'analysis'    => 'returns',
        ],
        'try_catch' => [
            'type'        => 'number',
            'unit'        => 'constructs',
            'description' => 'Try/catch constructs belonging to this callable, excluding nested callable scopes.',
            'source'      => 'Cosmira\\Soda\\Analysis\\CallableMetricsVisitor::tryCatchCountsByMethod',
            'analysis'    => 'tryCatch',
        ],
        'path' => [
            'type'        => 'string',
            'unit'        => 'text',
            'description' => 'File path with forward slashes.',
            'source'      => 'Cosmira\\Soda\\Analysis\\FileFacts::rows',
            'analysis'    => null,
        ],
        'name' => [
            'type'        => 'string',
            'unit'        => 'text',
            'description' => 'Qualified type or callable name.',
            'source'      => 'Cosmira\\Soda\\Analysis\\FileFacts::rows',
            'analysis'    => null,
        ],
        'namespace' => [
            'type'        => 'string',
            'unit'        => 'text',
            'description' => 'Declared namespace; empty for the global namespace.',
            'source'      => 'Cosmira\\Soda\\Analysis\\FileFacts::rows',
            'analysis'    => null,
        ],
    ],
];
