<?php

/**
 * @internal this code has been auto-generated by the phplrt compiler v4.0.3
 */

declare(strict_types=1);

\interface_exists(\Phplrt\Contracts\Source\Exception\SourceExceptionInterface::class);
\interface_exists(\Phplrt\Contracts\Source\ReadableInterface::class);
\interface_exists(\Phplrt\Contracts\Source\FileInterface::class);
\interface_exists(\Phplrt\Contracts\Lexer\ChannelInterface::class);
\interface_exists(\Phplrt\Contracts\Lexer\TokenInterface::class);
\interface_exists(\Phplrt\Contracts\Lexer\LexerInterface::class);
\interface_exists(\Phplrt\Contracts\Lexer\Exception\LexerExceptionInterface::class);
\interface_exists(\Phplrt\Contracts\Lexer\Exception\RuntimeExceptionInterface::class);
\enum_exists(\Phplrt\Contracts\Lexer\Channel::class);
\class_exists(\Phplrt\Contracts\Lexer\UserDefinedChannel::class);
\interface_exists(\Phplrt\Contracts\Parser\ParserInterface::class);
\interface_exists(\Phplrt\Contracts\Parser\Exception\ParserExceptionInterface::class);
\interface_exists(\Phplrt\Contracts\Parser\Exception\RuntimeExceptionInterface::class);

return new readonly class implements \Phplrt\Contracts\Parser\ParserInterface {
    /** @var int */
    public const int T_SPACE = 0;
    /** @var int */
    public const int T_SCOPE = 1;
    /** @var int */
    public const int T_WHERE = 2;
    /** @var int */
    public const int T_OR = 3;
    /** @var int */
    public const int T_AND = 4;
    /** @var int */
    public const int T_NOT = 5;
    /** @var int */
    public const int T_OPERATOR = 6;
    /** @var int */
    public const int T_NUMBER = 7;
    /** @var int */
    public const int T_STRING = 8;
    /** @var int */
    public const int T_FIELD = 9;

    protected readonly \Phplrt\Contracts\Parser\ParserInterface $parser;

    protected readonly \Phplrt\Contracts\Lexer\LexerInterface $lexer;

    public function __construct()
    {
        $this->lexer = new \Phplrt\Lexer\Lexer(
            pattern: '/\\G(?|(?:(?:\\s++)(*MARK:0))|(?:(?:(?:file|class|method)\\b)(*MARK:1))|(?:(?:where\\b)(*MARK:2))|(?:(?:or\\b)(*MARK:3))|(?:(?:and\\b)(*MARK:4))|(?:(?:not\\b)(*MARK:5))|(?:(?:>=|<=|!=|==|>|<|matches\\b)(*MARK:6))|(?:(?:-?\\d++(?:\\.\\d++)?)(*MARK:7))|(?:(?:"(?:[^"\\\\\\x00-\\x1f]|\\\\["\\\\\\/bfnrt]|\\\\u[0-9a-fA-F]{4})*")(*MARK:8))|(?:(?:[a-z_][a-z_0-9]*)(*MARK:9))|(?:(?:\\()(*MARK:10))|(?:(?:\\))(*MARK:11))|(?:(?:[^\\s]++)(*MARK:12)))/Ssum',
            channels: [
                'Hidden',
                12 => 'Unknown',
            ],
            names: [
                'T_SPACE',
                'T_SCOPE',
                'T_WHERE',
                'T_OR',
                'T_AND',
                'T_NOT',
                'T_OPERATOR',
                'T_NUMBER',
                'T_STRING',
                'T_FIELD',
            ],
        );

        $this->parser = new \Phplrt\Parser\Parser(
            lexer: $this->lexer,
            grammar: [
                new \Phplrt\Parser\Grammar\Concatenation([1, 2, 3]),
                new \Phplrt\Parser\Grammar\Lexeme(self::T_SCOPE, true),
                new \Phplrt\Parser\Grammar\Lexeme(self::T_WHERE, false),
                new \Phplrt\Parser\Grammar\Concatenation([4, 20]),
                new \Phplrt\Parser\Grammar\Concatenation([5, 17]),
                new \Phplrt\Parser\Grammar\Alternation([6, 8, 11]),
                new \Phplrt\Parser\Grammar\Concatenation([7, 5]),
                new \Phplrt\Parser\Grammar\Lexeme(self::T_NOT, false),
                new \Phplrt\Parser\Grammar\Concatenation([9, 3, 10]),
                new \Phplrt\Parser\Grammar\Lexeme(10, false),
                new \Phplrt\Parser\Grammar\Lexeme(11, false),
                new \Phplrt\Parser\Grammar\Concatenation([12, 13, 14]),
                new \Phplrt\Parser\Grammar\Lexeme(self::T_FIELD, true),
                new \Phplrt\Parser\Grammar\Lexeme(self::T_OPERATOR, true),
                new \Phplrt\Parser\Grammar\Alternation([15, 16]),
                new \Phplrt\Parser\Grammar\Lexeme(self::T_NUMBER, true),
                new \Phplrt\Parser\Grammar\Lexeme(self::T_STRING, true),
                new \Phplrt\Parser\Grammar\Repetition(18, 0, \INF),
                new \Phplrt\Parser\Grammar\Concatenation([19, 5]),
                new \Phplrt\Parser\Grammar\Lexeme(self::T_AND, false),
                new \Phplrt\Parser\Grammar\Repetition(21, 0, \INF),
                new \Phplrt\Parser\Grammar\Concatenation([22, 4]),
                new \Phplrt\Parser\Grammar\Lexeme(self::T_OR, false),
            ],
            initial: 0,
            reducers: [
                0 => self::reduceRule(...),
                3 => self::reduceAny(...),
                4 => self::reduceAll(...),
                6 => self::reduceNegation(...),
                8 => self::reduceGroup(...),
                11 => self::reduceComparison(...),
                15 => self::reduceNumber(...),
                16 => self::reduceText(...),
            ],
            lookahead: [
                [
                    1 => true,
                ],
                [
                    1 => true,
                ],
                [
                    2 => true,
                ],
                [
                    5 => true,
                    9 => true,
                    true,
                ],
                [
                    5 => true,
                    9 => true,
                    true,
                ],
                [
                    5 => true,
                    9 => true,
                    true,
                ],
                [
                    5 => true,
                ],
                [
                    5 => true,
                ],
                [
                    10 => true,
                ],
                [
                    10 => true,
                ],
                [
                    11 => true,
                ],
                [
                    9 => true,
                ],
                [
                    9 => true,
                ],
                [
                    6 => true,
                ],
                [
                    7 => true,
                    true,
                ],
                [
                    7 => true,
                ],
                [
                    8 => true,
                ],
                null,
                [
                    4 => true,
                ],
                [
                    4 => true,
                ],
                null,
                [
                    3 => true,
                ],
                [
                    3 => true,
                ],
            ],
            kept: [
                true,
                false,
                false,
                true,
                true,
                false,
                true,
                false,
                true,
                false,
                false,
                true,
                false,
                false,
                false,
                true,
                true,
                false,
                false,
                false,
                false,
                false,
                false,
            ],
            choicePrediction: [
                5 => [
                    5 => [
                        6,
                    ],
                    10 => [
                        8,
                    ],
                    9 => [
                        11,
                    ],
                ],
                14 => [
                    7 => [
                        15,
                    ],
                    [
                        16,
                    ],
                ],
            ],
            expectations: [
                'T_SPACE',
                'T_SCOPE',
                'T_WHERE',
                'T_OR',
                'T_AND',
                'T_NOT',
                'T_OPERATOR',
                'T_NUMBER',
                'T_STRING',
                'T_FIELD',
                '"("',
                '")"',
                '/[^\\s]++/',
            ],
        );
    }

    public function parse(\Phplrt\Contracts\Source\ReadableInterface $source): mixed
    {
        return $this->parser->parse($source);
    }

    private static function reduceRule(\Phplrt\Parser\Context $ctx, mixed $children): mixed
    {
        return (object) ['scope' => $children[0]->value, 'expression' => $children[1]];
    }

    private static function reduceAny(\Phplrt\Parser\Context $ctx, mixed $children): mixed
    {
        return count($children) === 1 ? $children[0] : (object) ['operator' => 'or', 'children' => $children];
    }

    private static function reduceAll(\Phplrt\Parser\Context $ctx, mixed $children): mixed
    {
        return count($children) === 1 ? $children[0] : (object) ['operator' => 'and', 'children' => $children];
    }

    private static function reduceNegation(\Phplrt\Parser\Context $ctx, mixed $children): mixed
    {
        return (object) ['operator' => 'not', 'children' => [$children[0]]];
    }

    private static function reduceGroup(\Phplrt\Parser\Context $ctx, mixed $children): mixed
    {
        return $children[0];
    }

    private static function reduceComparison(\Phplrt\Parser\Context $ctx, mixed $children): mixed
    {
        return (object) ['field' => $children[0]->value, 'operator' => $children[1]->value, 'value' => $children[2], 'offset' => $children[0]->offset];
    }

    private static function reduceNumber(\Phplrt\Parser\Context $ctx, mixed $children): mixed
    {
        return (float) $children->value;
    }

    private static function reduceText(\Phplrt\Parser\Context $ctx, mixed $children): mixed
    {
        return json_decode($children->value, true, 512, JSON_THROW_ON_ERROR);
    }
};
