<?php

declare(strict_types=1);

/**
 * Adversarial attack assigned to every built-in rule.
 *
 * The ten numbered executable snapshots exercise the ten architecture attacks.
 * The remaining attacks are grouped into the same ten review iterations and are
 * promoted to focused fixtures whenever an attack exposes a real blind spot.
 *
 * @return array<string, array{iteration: int, attack: non-empty-string}>
 */
return [
    'max_delegation_depth'            => ['iteration' => 100, 'attack' => 'Split a pass-through operation across several classes or private methods.'],
    'max_effective_methods_per_class' => ['iteration' => 100, 'attack' => 'Move methods into nested traits and rename them with private aliases.'],
    'max_effective_class_length'      => ['iteration' => 100, 'attack' => 'Move source into traits and import the same nested trait through a diamond.'],
    'no_mode_parameters'              => ['iteration' => 100, 'attack' => 'Replace a boolean flag with enum or string dispatch and hide the selector behind aliases.'],
    'no_repeated_type_dispatch'       => ['iteration' => 100, 'attack' => 'Repeat a type family using instanceof in one method and match or switch in another.'],
    'no_untyped_parameters'           => ['iteration' => 100, 'attack' => 'Remove a parameter type to evade type-based restrictions.'],
    'no_unused_private_state'         => ['iteration' => 100, 'attack' => 'Add a write-only private property or unused constant to make a wrapper appear stateful.'],
    'no_dependency_cycles'            => ['iteration' => 100, 'attack' => 'Use aliases and nested namespaces to hide a cycle between modules.'],
    'no_empty_local_interfaces'       => ['iteration' => 100, 'attack' => 'Give a decorative marker a constant or an empty parent interface.'],
    'no_redundant_local_interfaces'   => ['iteration' => 100, 'attack' => 'Declare an interface and implement or import it without any type consumer.'],
    'no_unused_parameters'            => ['iteration' => 100, 'attack' => 'Use a same-named variable only in a nested callable to disguise an unused input.'],

    'max_method_length'                  => ['iteration' => 1, 'attack' => 'Hide a long workflow in closure bodies and fluent callbacks.'],
    'max_class_length'                   => ['iteration' => 1, 'attack' => 'Spread a god object across comments, traits, and anonymous helpers.'],
    'max_arguments'                      => ['iteration' => 1, 'attack' => 'Replace parameters with variadics, arrays, and ambient lookup.'],
    'max_methods_per_class'              => ['iteration' => 1, 'attack' => 'Generate behavior through magic methods and inherited surface area.'],
    'max_file_loc'                       => ['iteration' => 1, 'attack' => 'Inflate physical lines with comments while hiding dense logical code.'],
    'max_line_length'                    => ['iteration' => 1, 'attack' => 'Split one opaque expression across many short physical lines.'],
    'max_properties_per_class'           => ['iteration' => 2, 'attack' => 'Move state into one untyped array property.'],
    'max_public_methods'                 => ['iteration' => 2, 'attack' => 'Expose behavior through __call instead of declared public methods.'],
    'max_dependencies'                   => ['iteration' => 2, 'attack' => 'Pull collaborators from a container inside method bodies.'],
    'max_todo_fixme_comments'            => ['iteration' => 2, 'attack' => 'Encode debt as XXX, HACK, and deliberately vague prose.'],
    'max_commented_out_code_lines'       => ['iteration' => 2, 'attack' => 'Leave dead code as pseudocode with altered spacing.'],
    'max_empty_catch_blocks'             => ['iteration' => 2, 'attack' => 'Put a meaningless assignment in catch so it is technically non-empty.'],
    'max_ask_then_tell_patterns'         => ['iteration' => 3, 'attack' => 'Alias the receiver and query through an accessor chain before mutation.'],
    'no_trivial_delegating_classes'      => ['iteration' => 3, 'attack' => 'Add logging or a decorative condition to a pass-through wrapper.'],
    'methods_follow_call_order'          => ['iteration' => 3, 'attack' => 'Dispatch helpers indirectly through callable variables.'],
    'only_list_arrays'                   => ['iteration' => 4, 'attack' => 'Build associative shape incrementally instead of as an array literal.'],
    'no_numeric_array_index'             => ['iteration' => 4, 'attack' => 'Hide numeric positions behind constants and arithmetic expressions.'],
    'unused_methods'                     => ['iteration' => 4, 'attack' => 'Invoke dead-looking methods dynamically or only through framework convention.'],
    'useless_variable'                   => ['iteration' => 4, 'attack' => 'Pass an alias through closure capture before returning it unchanged.'],
    'no_assignment_in_condition'         => ['iteration' => 4, 'attack' => 'Move mutation into a called predicate used by the condition.'],
    'no_else_branches'                   => ['iteration' => 4, 'attack' => 'Replace else with ternary and switch expressions.'],
    'no_complex_control_conditions'      => ['iteration' => 5, 'attack' => 'Hide several decisions behind one deceptively named predicate call.'],
    'no_service_locator_calls'           => ['iteration' => 5, 'attack' => 'Rename app/resolve behind a project helper or container method.'],
    'no_singleton_access'                => ['iteration' => 16, 'attack' => 'Expose a global collaborator through a respectable instance() factory.'],
    'no_reflection'                      => ['iteration' => 17, 'attack' => 'Call reflective construction a metadata-driven hydrator.'],
    'no_runtime_hooks'                   => ['iteration' => 18, 'attack' => 'Move side effects into shutdown and error-handler callbacks.'],
    'no_runtime_code_evaluation'         => ['iteration' => 20, 'attack' => 'Compile tenant policy by evaluating generated PHP source.'],
    'no_process_configuration_mutation'  => ['iteration' => 22, 'attack' => 'Mutate ini, cwd, locale, and timezone from application services.'],
    'no_direct_response_globals'         => ['iteration' => 26, 'attack' => 'Emit headers, cookies, and sessions from domain-looking workflows.'],
    'no_symbol_table_mutation'           => ['iteration' => 29, 'attack' => 'Hydrate context into local variables with extract().'],
    'no_implicit_arguments'              => ['iteration' => 30, 'attack' => 'Keep an empty signature and recover hidden inputs with func_get_args().'],
    'no_direct_filesystem_mutation'      => ['iteration' => 31, 'attack' => 'Perform storage writes, deletes, moves, and provisioning directly.'],
    'no_subprocess_execution'            => ['iteration' => 35, 'attack' => 'Hide native commands behind adapter and gateway vocabulary.'],
    'no_native_deserialization'          => ['iteration' => 39, 'attack' => 'Decode trusted broker envelopes with native unserialize().'],
    'no_runtime_includes'                => ['iteration' => 40, 'attack' => 'Load executable policy from a colocated include file.'],
    'no_runtime_type_aliases'            => ['iteration' => 41, 'attack' => 'Keep legacy consumers alive through runtime class_alias().'],
    'no_dynamic_properties'              => ['iteration' => 42, 'attack' => 'Model partner payloads with AllowDynamicProperties.'],
    'no_anonymous_classes'               => ['iteration' => 43, 'attack' => 'Hide strategy types inside anonymous class expressions.'],
    'no_object_cloning'                  => ['iteration' => 45, 'attack' => 'Call clone an immutable prototype-forking protocol.'],
    'no_closure_rebinding'               => ['iteration' => 46, 'attack' => 'Use Closure bind APIs to bypass visible scope ownership.'],
    'no_runtime_contract_probes'         => ['iteration' => 48, 'attack' => 'Negotiate capabilities with method/property/callable probes.'],
    'no_global_state'                    => ['iteration' => 5, 'attack' => 'Move process-wide mutation into a static property.'],
    'no_environment_reads'               => ['iteration' => 5, 'attack' => 'Read configuration through $_SERVER or a wrapper helper.'],
    'no_error_suppression'               => ['iteration' => 5, 'attack' => 'Install a temporary error handler that discards diagnostics.'],
    'no_dynamic_invocation'              => ['iteration' => 5, 'attack' => 'Use reflection, call_user_func, or an invokable object.'],
    'no_catch_all_exceptions'            => ['iteration' => 6, 'attack' => 'Alias Throwable or catch a broad project base exception.'],
    'no_boolean_parameters'              => ['iteration' => 6, 'attack' => 'Use nullable bool, union bool, or an integer mode flag.'],
    'no_behavior_magic_methods'          => ['iteration' => 6, 'attack' => 'Move the hidden API to a trait or an invokable object.'],
    'no_static_mutable_properties'       => ['iteration' => 6, 'attack' => 'Hide shared state inside a static local variable or singleton instance.'],
    'no_blocking_sleep'                  => ['iteration' => 6, 'attack' => 'Block through time_nanosleep, stream_select, or a wrapper.'],
    'max_efferent_coupling'              => ['iteration' => 6, 'attack' => 'Refer to dependencies through strings, reflection, and container keys.'],
    'max_classes_per_file'               => ['iteration' => 7, 'attack' => 'Use anonymous classes and enum cases as miniature hidden types.'],
    'max_namespace_depth'                => ['iteration' => 7, 'attack' => 'Encode hierarchy into long class prefixes in a shallow namespace.'],
    'max_classes_per_namespace'          => ['iteration' => 7, 'attack' => 'Create near-identical numbered child namespaces.'],
    'max_layer_dominance_percentage'     => ['iteration' => 7, 'attack' => 'Rename technical layers with domain-sounding synonyms.'],
    'max_traits_per_class'               => ['iteration' => 7, 'attack' => 'Use one trait that recursively imports many traits.'],
    'max_interfaces_per_class'           => ['iteration' => 7, 'attack' => 'Inherit many interface obligations through one umbrella interface.'],
    'max_classes_per_project'            => ['iteration' => 7, 'attack' => 'Replace named classes with anonymous classes and generated proxies.'],
    'max_cyclomatic_complexity'          => ['iteration' => 8, 'attack' => 'Replace branches with lookup tables, callbacks, exceptions, and boolean arithmetic.'],
    'max_control_nesting'                => ['iteration' => 8, 'attack' => 'Flatten nesting into a long sequence of guards with shared mutation.'],
    'max_return_statements'              => ['iteration' => 8, 'attack' => 'Use one return and mutate a result through many branches.'],
    'max_boolean_conditions'             => ['iteration' => 8, 'attack' => 'Replace boolean operators with nested predicate calls and bitwise operators.'],
    'max_try_catch_blocks'               => ['iteration' => 8, 'attack' => 'Move recovery into promise callbacks and error-handler functions.'],
    'avoid_redundant_naming'             => ['iteration' => 10, 'attack' => 'Repeat concepts through synonyms rather than identical tokens.'],
    'boolean_methods_without_prefix'     => ['iteration' => 10, 'attack' => 'Return bool through unions, aliases, or inferred return types.'],
    'variable_name_length'               => ['iteration' => 10, 'attack' => 'Choose short but meaningless names that satisfy the range.'],
    'method_name_length'                 => ['iteration' => 10, 'attack' => 'Use a short generic verb for a method with many responsibilities.'],
    'class_name_length'                  => ['iteration' => 10, 'attack' => 'Use a short prestigious suffix such as Manager for a god object.'],
    'namespace_name_length'              => ['iteration' => 10, 'attack' => 'Use short meaningless nested namespace segments.'],
    'no_trivial_factories'               => [
        'iteration' => 3,
        'attack'    => 'Rename create to build; this deliberately leaves the narrow factory scope.',
    ],
    'no_repeated_compound_conditions' => [
        'iteration' => 3,
        'attack'    => 'Hide the condition behind a call; this check only compares syntax.',
    ],
];
